// Weekly ping to Supabase so the free-tier project doesn't get auto-paused
// after 7 days of inactivity. Triggered by the Vercel Cron in vercel.json.
import { createClient } from "@supabase/supabase-js";
import { NextRequest, NextResponse } from "next/server";

export async function GET(req: NextRequest) {
  // CRON_SECRET is NOT auto-generated by Vercel — you must create it yourself in
  // Project Settings → Environment Variables. Once it exists, Vercel automatically
  // sends it as the Authorization Bearer header on cron-triggered requests.
  const authHeader = req.headers.get("authorization");
  const cronSecret = process.env.CRON_SECRET;

  if (!cronSecret) {
    // Fail closed in production: an unset secret must not silently open the endpoint.
    if (process.env.NODE_ENV === "production") {
      return NextResponse.json(
        { error: "CRON_SECRET is not set — add it in Vercel Project Settings → Environment Variables" },
        { status: 500 }
      );
    }
  } else if (authHeader !== `Bearer ${cronSecret}`) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  }

  const supabase = createClient(
    process.env.NEXT_PUBLIC_SUPABASE_URL!,
    process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!
  );

  const { data, error } = await supabase
    .from("event_types")
    .select("id")
    .limit(1);

  if (error) {
    return NextResponse.json({ ok: false, error: error.message }, { status: 500 });
  }

  return NextResponse.json({ ok: true, checkedAt: new Date().toISOString(), rows: data?.length ?? 0 });
}
