// Weekly ping to Supabase so the free-tier project doesn't get auto-paused
// after 7 days of inactivity. Triggered by the Vercel Cron in vercel.json.
import { createClient } from "@supabase/supabase-js";
import { NextRequest, NextResponse } from "next/server";

export async function GET(req: NextRequest) {
  // CRON_SECRET is NOT auto-generated by Vercel — you must create it yourself in
  // Project Settings → Environment Variables. Once it exists, Vercel automatically
  // sends it as the Authorization Bearer header on cron-triggered requests.
  //
  // This endpoint only reads already-public catalog data with the anon key (no
  // mutation, no PII), so it fails OPEN rather than closed: the whole point of
  // this route is to stop Supabase from auto-pausing, and a missing/misconfigured
  // secret must never silently defeat that — it only downgrades to a warning.
  const authHeader = req.headers.get("authorization");
  const cronSecret = process.env.CRON_SECRET;
  const authenticated = !cronSecret || authHeader === `Bearer ${cronSecret}`;

  if (!authenticated) {
    console.warn("[keep-alive] CRON_SECRET mismatch — ping still executed, but request was not verified as coming from Vercel Cron");
  }

  const supabase = createClient(
    process.env.NEXT_PUBLIC_SUPABASE_URL!,
    process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!
  );

  const { data, error } = await supabase
    .from("event_types")
    .select("id")
    .limit(1);

  if (error) {
    return NextResponse.json({ ok: false, error: error.message, authenticated }, { status: 500 });
  }

  return NextResponse.json({
    ok: true,
    checkedAt: new Date().toISOString(),
    rows: data?.length ?? 0,
    ...(cronSecret && !authenticated ? { warning: "CRON_SECRET mismatch — check Vercel env var" } : {}),
  });
}
